# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 616abf8a765a0cb698bba27ff36a4d09ce0ec394507917748d06d3b771635a1e63c6f6e5b76a736c52f09663f28fb46debc9dc355f4ba75d427b1ac6fb35296b

test:
  secret_key_base: 315e78134bdf44bf3f476a8639aed0f1704a1ccfa8fc867c38d3380013f581c34d82b52627b2a8ae4d976cc4cd2d6703b5ca21fbcf83e0415d9bd0023cc3d0d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
